# permissions for end users to view units.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit-viewer-role
rules:
- apiGroups:
  - custom.unit.crd.com
  resources:
  - units
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - custom.unit.crd.com
  resources:
  - units/status
  verbs:
  - get
