apiVersion: v1
kind: Service
metadata:
  name: kunit-webhook-service
  namespace: kunit-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kunit-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: kunit-webhook-service
        namespace: kunit-system
        path: /mutate-custom-unit-crd-com-v1-unit
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: munit.kb.io
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - custom.unit.crd.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - units
        scope: '*'
    sideEffects: Unknown
    timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kunit-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: kunit-webhook-service
        namespace: kunit-system
        path: /validate-custom-unit-crd-com-v1-unit
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: vunit.kb.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:
          - custom.unit.crd.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - units
        scope: '*'
    sideEffects: Unknown
    timeoutSeconds: 30